### ISSUE TITLE
Update error and notice message presentation

### ISSUE THREAD

**Issue by dodie** [dodie/time-admin#53]
Error and notice messages appear quite ugly, see the screenshot below. 

![image](https://cloud.githubusercontent.com/assets/1114220/20868443/58756992-ba5c-11e6-8340-1603593c2b0b.png)

The error messages could be presented in a modal dialog, while the other messages could use use a less disruptive mechanism, such as toast notification.

**Comment by suliatis** [comment]
I think it would be much nicer than a modal dialog: http://getbootstrap.com/components/#alerts-dismissible
