### ISSUE TITLE
Interval selector on "Tasksheet" page

### ISSUE THREAD

**Issue by suliatis** [dodie/time-admin#58]
Clients should be able to query bigger intervals than one month on "Tasksheet" page, similarly to "Tasksheet Summary" page. The scale of the tasksheet would change dynamically based on the size of the selected interval.

**Comment by dodie** [comment]
I think Tasksheet and Tasksheet Summary pages should be merged. A user with only client permission could not select other users. If only one month is queried then the scale should change to display days instead of months.

**Comment by dodie** [comment]
Nice!
