### ISSUE TITLE
Inactive users in reports

### ISSUE THREAD

**Issue by dodie** [dodie/time-admin#61]
If a user starts a task, but never terminates it with a Pause, all the reports in the future will be skewed. It would be better to automatically terminate these task items after a while (eg. 24 hours).

**Comment by suliatis** [comment]
Or we can pause last active task on user inactivation.

**Comment by dodie** [comment]
The same problem occurs when somebody going to have a long vacation and forget to hit Pause.
I don't think there is a real use-case where somebody works more than 24h in a row (on the same task), but we can use larger threshold.
