### ISSUE TITLE
Pause task is visible on timesheet

### ISSUE THREAD

**Issue by dodie** [dodie/time-admin#91]
Steps to reproduce:
- Create normal entries to a day. For example, start to work on Task1 from 10:00 and start pause from 11:00.
- Create an additional Pause entry from 9:00.
- Go to the Timesheet page, and notice that the start time is 9:00 rather than 10:00, and the sum time is 2 hours instead of one.

The bug does not affect the Task and the Tasksheet page.

**Comment by suliatis** [comment]
With the recent version I can not reproduce this issue.

**Comment by dodie** [comment]
You are right, the steps mentioned in the issue are not sufficient to reproduce the issue.
It seems that the bug only appears if there is recorded data for a previous day.

So, for example, doing the original steps in the issue seems to produce correct behavior:
![image](https://user-images.githubusercontent.com/1114220/36053277-6a24290a-0df1-11e8-9a0a-a90cd08b5371.png)

But adding one hour to a previous day makes the bug appear (notice the different arrival time for 02.09):
![image](https://user-images.githubusercontent.com/1114220/36053452-09f1ca0a-0df2-11e8-92af-b92e6d3483a4.png)

**Comment by dodie** [comment]
I've filtered the pause tasks at the beginning of each day. Seems fine for now, tested for a couple of use-cases.
